GET http://localhost:4000/borrowedBooks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblVzZXIiOiJmb2xpdGVnYXZAbWFpbGluYXRvci5jb20iLCJwYXNzd29yZFVzZXIiOiIyMjIiLCJpYXQiOjE2Nzk2MTQxMzUsImV4cCI6MTY3OTYxNDE1NX0.mGR2Zu53wjplXmxEOD4bDXAVvBcsNLHs9rCM9TqnK50
###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpblVzZXIiOiJmb2xpdGVnYXZAbWFpbGluYXRvci5jb20iLCJwYXNzd29yZFVzZXIiOiIyMjIiLCJpYXQiOjE2Nzk2MTQxMzV9.3ViZ100BoP-7-EFziPc67W0cI0-dzByh1ihvdvSED9U"
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
          "loginUser": "folitegav@mailinator.com",
          "passwordUser": "222"
}

