GET http://localhost:4000/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZFVzZXIiOiIxMjMiLCJpYXQiOjE2Nzc3NTk5MzcsImV4cCI6MTY3Nzc1OTk1N30.9fKljoUauJxhIA4xQ-udcq_jZT67GVKHNOv9eA1Sk3k
###

POST http://localhost:5000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjc3NjkxMDM0fQ.H3vumPPHMOd1bv2nr7hu74rzj0RfG5zajasWcPPMyQM"
}
###

POST http://localhost:5000/login
Content-Type: application/json

{
          "registerUser": "www",
          "passwordUser": "123"
}

